#!/bin/bash

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
    echo "You can't push to master branch" 
	exit 1
else

	echo "Your branch is :${current_branch}"
	sbt compile
	compiles =$?
	if [$compiles -eg 0]
	then 
		echo "Progect compile"
		exit 0 # push will execute
	else 
		echo "sbt compile wasn't success"
		exit 0 # push will execute
	
	fi
fi